version: '3.2'
services:
  web:
    build: ./
    ports:
      - "${PORT:-3000}:5000"
    volumes:
      - ./:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/development?sslmode=disable
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:9
    expose:
      - 5432
    volumes:
      - sinatra-pg-data:/var/lib/postgresql/data
volumes:
  sinatra-pg-data:
    external: true